### ISSUE TITLE
name headerLayout is generic and may conflict with navigation drawer implementation

### ISSUE THREAD

**Issue by swolfand** [traex/ExpandableLayout#33]
at least a few people have had the issue where they use a headerLayout as the name for the navigation drawer header layout, which causes generated build files to have conflicts here is one other example on [stackoverflow](http://stackoverflow.com/questions/31903319/android-design-support-and-other-library-give-gradle-build-error-headerlayout) I would suggest changing the name to something like **fixedHeaderLayout** for example

**Comment by HectorFGarcia** [comment]
I have that exact problem with this lib, I can't use it because I have an "Attribute "headerLayout" has already been defined" error.

**Comment by vaibhavgupta** [comment]
Any update on this issue ?

**Comment by vaibhavgupta** [comment]
Hi the attributes names were changed to avoid collision in the library.

https://github.com/traex/ExpandableLayout/blob/master/library/src/main/res/values/attrs.xml

Its not published on the maven central i guess, because when i used that it didn't work.

**Comment by ghost** [comment]
The solution is quite easy, just use the below dependencie instead of the one shown in the readme:

compile 'com.github.traex.expandablelayout:library:1.3'

**Comment by sheat2500** [comment]
This kills me 2 hours...I should always check the issue section first. .
Thank you guys..

**Comment by kscMaster** [comment]
I did what you meant, but it happened.
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

did you meet this problem?

**Comment by swolfand** [comment]
This has been fixed in the latest version
